program: Sweep2d.py
name: MagAE_2D_Div_Curl
project: MagAE_2D_hp-tuning
entity: te-st

method: random

metric:
  name: test_mape
  goal: minimize

parameters:
  lr: 
    values: [0.001, 0.0005, 0.0001]
  
  batch_size:
    values: [32, 64, 128]
    
  div_alpha:
    values: [0.01, 0.1, 1.0]
  
  curl_alpha:
    values: [0.1, 1, 10.0]

  cnum:
    values: [16, 32, 64]
